=== inveniosoftware/datacite/datacite/schemas/datacite-v3.1.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "datacite-v3.1.json",
  "title": "DataCite v3.1",
  "description": "JSON representation of the DataCite v3.1 schema.",
  "additionalProperties": false,
  "definitions": {
    "doi": {
      "description": "Digital object identifier.",
      "type": "string",
      "pattern": "10\\..+/.+"
    },
    "year": {
      "type": "string"
    },
    "language": {
      "description": "Allowed values are taken from IETF BCP 47, ISO 639-1 language codes.",
      "type": "string"
    },
    "uri": {
      "description": "For adding future URI validation.",
      "type": "string"
    },
    "nameIdentifier": {
      "type": "object",
      "properties": {
        "nameIdentifier": {
          "type": "string"
        },
        "nameIdentifierScheme": {
          "type": "string"
        },
        "schemeURI": {
          "$ref": "#/definitions/uri"
        }
      },
      "required": [
        "nameIdentifier",
        "nameIdentifierScheme"
      ]
    },
    "person": {
      "type": "object",
      "properties": {

      },
      "required": [
        "name"
      ]
    }
  },
  "type": "object",
  "properties": {
    "identifier": {
      "description": "A persistent identifier that identifies a resource. Currently, only DOI is allowed.",
      "type": "object",
      "properties": {
        "identifier": {
          "$ref": "#/definitions/doi"
        },
        "identifierType": {
          "enum": [
            "DOI"
          ]
        }
      },
      "required": [
        "identifier",
        "identifierType"
      ]
    },
    "creators": {
      "description": "The main researchers involved working on the data, or the authors of the publication in priority order. May be a corporate/institutional or personal name. Format: Family, Given",
      "type": "array",
      "items": {
        "creatorName": {
          "type": "string"
        },
        "nameIdentifier": {
          "$ref": "#/definitions/nameIdentifier"
        },
        "affiliation": {
          "type": "string"
        }
      },
      "required": [
        "creatorName"
      ]
    },
    "titles": {
      "type": "array",
      "items": {
        "description": "A name or title by which a resource is known.",
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "minLength": 1
          },
          "type": {
            "description": "WARNING: This field has been superseded by 'titleType'.",
            "enum": [
              "AlternativeTitle",
              "Subtitle",
              "TranslatedTitle"
            ]
          },
          "titleType": {
            "enum": [
              "AlternativeTitle",
              "Subtitle",
              "TranslatedTitle"
            ]
          },
          "lang": {
            "$ref": "#/definitions/language"
          }
        },
        "required": [
          "title"
        ]
      }
    },
    "publisher": {
      "description": "The name of the entity that holds, archives, publishes prints, distributes, releases, issues, or produces the resource. This property will be used to formulate the citation, so consider the prominence of the role. In the case of datasets, \"publish\" is understood to mean making the data available to the community of researchers.",
      "type": "string",
      "minLength": 1
    },
    "publicationYear": {
      "description": "Year when the data is made publicly available. If an embargo period has been in effect, use the date when the embargo period ends. In the case of datasets, \"publish\" is understood to mean making the data available on a specific date to the community of researchers. If there is no standard publication year value, use the date that would be preferred from a citation perspective.",
      "$ref": "#/definitions/year"
    },
    "subjects": {
      "type": "array",
      "items": {
        "description": "Subject, keywords, classification codes, or key phrases describing the resource.",
        "type": "object",
        "properties": {
          "subject": {
            "type": "string"
          },
          "subjectScheme": {
            "type": "string"
          },
          "schemeURI": {
            "$ref": "#/definitions/uri"
          },
          "lang": {
            "$ref": "#/definitions/language"
          }
        }
      }
    },
    "contributors": {
      "description": "The institution or person responsible for collecting, creating, or otherwise contributing to the developement of the dataset. The personal name format should be: Family, Given.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "contributorType": {
            "enum": [
              "ContactPerson",
              "DataCollector",
              "DataCurator",
              "DataManager",
              "Distributor",
              "Editor",
              "Funder",
              "HostingInstitution",
              "Other",
              "Producer",
              "ProjectLeader",
              "ProjectManager",
              "ProjectMember",
              "RegistrationAgency",
              "RegistrationAuthority",
              "RelatedPerson",
              "ResearchGroup",
              "RightsHolder",
              "Researcher",
              "Sponsor",
              "Supervisor",
              "WorkPackageLeader"
            ]
          },
          "contributorName": {
            "type": "string"
          },
          "nameIdentifier": {
            "$ref": "#/definitions/nameIdentifier"
          },
          "affiliation": {
            "type": "string"
          }
        },
        "required": [
          "contributorName",
          "contributorType"
        ]
      }
    },
    "dates": {
      "description": "Different dates relevant to the work.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "date": {
            "description": "YYYY,YYYY-MM-DD, YYYY-MM-DDThh:mm:ssTZD or any other format or level of granularity described in W3CDTF. Use RKMS-ISO8601 standard for depicting date ranges.",
            "type": "string"
          },
          "dateType": {
            "enum": [
              "Accepted",
              "Available",
              "Collected",
              "Copyrighted",
              "Created",
              "Issued",
              "Submitted",
              "Updated",
              "Valid"
            ]
          }
        }
      }
    },
    "language": {
      "description": "Primary language of the resource.",
      "$ref": "#/definitions/language"
    },
    "resourceType": {
      "description": "The type of a resource. You may enter an additional free text description. The format is open, but the preferred format is a single term of some detail so that a pair can be formed with the sub-property.",
      "type": "object",
      "properties": {
        "resourceType": {
          "type": "string"
        },
        "resourceTypeGeneral": {
          "description": "The general type of a resource.",
          "enum": [
            "Audiovisual",
            "Collection",
            "Dataset",
            "Event",
            "Image",
            "InteractiveResource",
            "Model",
            "PhysicalObject",
            "Service",
            "Software",
            "Sound",
            "Text",
            "Workflow",
            "Other"
          ]
        }
      },
      "required": [
        "resourceTypeGeneral"
      ]
    },
    "alternateIdentifiers": {
      "description": "An identifier or identifiers other than the primary Identifier applied to the resource being registered. This may be any alphanumeric string which is unique within its domain of issue. May be used for local identifiers. AlternateIdentifier should be used for another identifier of the same instance (same location, same file).",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "alternateIdentifier": {
            "type": "string"
          },
          "alternateIdentifierType": {
            "type": "string"
          }
        },
        "required": [
          "alternateIdentifier",
          "alternateIdentifierType"
        ]
      }
    },
    "relatedIdentifiers": {
      "description": "Identifiers of related resources. Use this property to indicate subsets of properties, as appropriate.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "relatedIdentifier": {
            "type": "string"
          },
          "relatedIdentifierType": {
            "enum": [
              "ARK",
              "arXiv",
              "bibcode",
              "DOI",
              "EAN13",
              "EISSN",
              "Handle",
              "ISBN",
              "ISSN",
              "ISTC",
              "LISSN",
              "LSID",
              "PMID",
              "PURL",
              "UPC",
              "URL",
              "URN"
            ]
          },
          "relationType": {
            "enum": [
              "IsCitedBy",
              "Cites",
              "IsSupplementTo",
              "IsSupplementedBy",
              "IsContinuedBy",
              "Continues",
              "IsNewVersionOf",
              "IsPreviousVersionOf",
              "IsPartOf",
              "HasPart",
              "IsReferencedBy",
              "References",
              "IsDocumentedBy",
              "Documents",
              "IsCompiledBy",
              "Compiles",
              "IsVariantFormOf",
              "IsOriginalFormOf",
              "IsIdenticalTo",
              "HasMetadata",
              "IsMetadataFor",
              "Reviews",
              "IsReviewedBy",
              "IsDerivedFrom",
              "IsSourceOf"
            ]
          },
          "relatedMetadataScheme": {
            "type": "string"
          },
          "schemeURI": {
            "$ref": "#/definitions/uri"
          }
        },
        "required": [
          "relatedIdentifier",
          "relationType",
          "relatedIdentifierType"
        ]
      }
    },
    "sizes": {
      "description": "Unstructures size information about the resource.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "formats": {
      "description": "Technical format of the resource. Use file extension or MIME type where possible.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "version": {
      "description": "Version number of the resource. If the primary resource has changed the version number increases. Register a new identifier for a major version change. Individual stewards need to determine which are major vs. minor versions. May be used in conjunction with properties 11 and 12 (AlternateIdentifier and RelatedIdentifier) to indicate various information updates. May be used in conjunction with property 17 (Description) to indicate the nature and file/record range of version.",
      "type": "string"
    },
    "rightsList": {
      "description": "Any rights information for this resource. Provide a rights management statement for the resource or reference a service providing such information. Include embargo information if applicable. Use the complete title of a license and include version information if applicable.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "rightsURI": {
            "$ref": "#/definitions/uri"
          },
          "rights": {
            "type": "string"
          }
        }
      }
    },
    "descriptions": {
      "description": "All additional information that does not fit in any of the other categories. May be used for technical information. It is a best practice to supply a description.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string",
            "minLength": 1
          },
          "descriptionType": {
            "type": "string",
            "description": "The type of the description.",
            "enum": [
              "Abstract",
              "Methods",
              "SeriesInformation",
              "TableOfContents",
              "Other"
            ]
          },
          "lang": {
            "$ref": "#/definitions/language"
          }
        },
        "required": [
          "description",
          "descriptionType"
        ]
      }
    },
    "geoLocations": {
      "description": "Spatial region or named place where the data was gathered or about which the data is focused.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "geoLocationPoint": {
            "type": "string"
          },
          "geoLocationBox": {
            "type": "string"
          },
          "geoLocationPlace": {
            "type": "string"
          }
        }
      }
    }
  },
  "required": [
    "identifier",
    "creators",
    "titles",
    "publisher",
    "publicationYear"
  ]
}

=== inveniosoftware/datacite/tests/data/datacite-v3.1-full-example.json
{
  "identifier": {
    "identifier": "10.1234/example-full",
    "identifierType": "DOI"
  },
  "creators": [
    {
      "creatorName": "Miller, Elizabeth",
      "nameIdentifier": {
        "nameIdentifier": "0000-0001-5000-0007",
        "nameIdentifierScheme": "ORCID",
        "schemeURI": "http://orcid.org/"
      },
      "affiliation": "DataCite"
    }
  ],
  "titles": [
    {
      "title": "Full DataCite XML Example",
      "lang": "en-us"
    },
    {
      "title": "Demonstration of DataCite Properties.",
      "titleType": "Subtitle",
      "lang": "en-us"
    }
  ],
  "publisher": "DataCite",
  "publicationYear": "2014",
  "subjects": [
    {
      "subject": "000 computer science",
      "subjectScheme": "dewey",
      "schemeURI": "http://dewey.info/",
      "lang": "en-us"
    }
  ],
  "contributors": [
    {
      "contributorName": "Starr, Joan",
      "contributorType": "ProjectLeader",
      "nameIdentifier": {
        "nameIdentifier": "0000-0002-7285-027X",
        "nameIdentifierScheme": "ORCID",
        "schemeURI": "http://orcid.org/"
      },
      "affiliation": "California Digital Library"
    }
  ],
  "dates": [
    {
      "date": "2014-10-17",
      "dateType": "Updated"
    }
  ],
  "language": "en-us",
  "resourceType": {
    "resourceTypeGeneral": "Software",
    "resourceType": "XML"
  },
  "alternateIdentifiers": [
    {
      "alternateIdentifier": "http://schema.datacite.org/schema/meta/kernel-3.1/example/datacite-example-full-v3.1.xml",
      "alternateIdentifierType": "URL"
    }
  ],
  "relatedIdentifiers": [
    {
      "relatedIdentifier": "http://data.datacite.org/application/citeproc+json/10.1234/example-full",
      "relatedIdentifierType": "URL",
      "relationType": "HasMetadata",
      "relatedMetadataScheme": "citeproc+json",
      "schemeURI": "https://github.com/citation-style-language/schema/raw/master/csl-data.json"
    },
    {
      "relatedIdentifier": "arXiv:0706.0001",
      "relatedIdentifierType": "arXiv",
      "relationType": "IsReviewedBy"
    }
  ],
  "sizes": [
    "3KB"
  ],
  "formats": [
    "application/xml"
  ],
  "version": "3.1",
  "rightsList": [
    {
      "rights": "CC0 1.0 Universal",
      "rightsURI": "http://creativecommons.org/publicdomain/zero/1.0/"
    }
  ],
  "descriptions": [
    {
      "descriptionType": "Abstract",
      "lang": "en-us",
      "description": "XML example of all DataCite Metadata Schema v3.1 properties."
    }
  ],
  "geoLocations": [
    {
      "geoLocationPoint": "31.233 -67.302",
      "geoLocationBox": "41.090 -71.032  42.893 -68.211",
      "geoLocationPlace": "Atlantic Ocean"
    }
  ]
}
